export const reactions = [
  {name: 'James', photo: require(`../../../assets/MessengerAssets/Ellipse_19.png`), isActive: true},
  {name: 'Jessica', photo: require(`../../../assets/MessengerAssets/Ellipse_147.png`), isActive: false},
];

export const chats = [
  {
    name: `Jessica Parker`,
    lastMessage: {
      type: `text`,
      text: `How your life is going?`,
      audioLength: ``,
      photo: ``,
    },
    time: `29 min ago`,
    notifications: 1,
    isTyping: false,
    delivered: false,
    seen: false,
    photo: [`Elipse 11.png`],
  },
  {
    name: `James, Beth`,
    lastMessage: {
      type: `text`,
      text: `Wow, that's awesome!`,
      audioLength: ``,
      photo: ``,
    },
    time: `31 min ago`,
    notifications: 7,
    isTyping: false,
    delivered: false,
    seen: false,
    photo: [`Oval.png`, `Oval2.png`],
  },
  {
    name: `Brandon Wilson`,
    lastMessage: {
      type: `text`,
      text: ``,
      audioLength: ``,
      photo: ``,
    },
    time: `2 hours ago`,
    notifications: 0,
    isTyping: true,
    delivered: false,
    seen: false,
    photo: [`Elipse 18.png`],
  },
  {
    name: `James miles`,
    lastMessage: {
      type: `audio`,
      text: ``,
      audioLength: `01:27`,
      photo: ``,
    },
    time: `1 hour ago`,
    notifications: 0,
    isTyping: false,
    delivered: false,
    seen: false,
    photo: [`Elipse 18.png`],
  },
  {
    name: `Zach spencer`,
    lastMessage: {
      type: `text`,
      text: `Yeah of course, just text me!`,
      audioLength: ``,
      photo: ``,
    },
    time: `1 hour ago`,
    notifications: 0,
    isTyping: false,
    delivered: true,
    seen: false,
    photo: [`Elipse 12.png`],
  },
  {
    name: `Andrew Sorbo`,
    lastMessage: {
      type: `text`,
      text: `😂😂😂😂`,
      audioLength: ``,
      photo: ``,
    },
    time: `1 hour ago`,
    notifications: 0,
    isTyping: false,
    delivered: false,
    seen: true,
    photo: [`Elipse 16.png`],
  },
  {
    name: `Leslie Robertson`,
    lastMessage: {
      type: `text`,
      text: `It's by the door`,
      audioLength: ``,
      photo: ``,
    },
    time: `2 hours ago`,
    notifications: 0,
    isTyping: false,
    delivered: false,
    seen: false,
    photo: [`Elipse 17.png`],
  },
  {
    name: `Sara mello`,
    lastMessage: {
      type: `photo`,
      text: ``,
      audioLength: ``,
      photo: `SentPhoto`,
    },
    time: `1 hour ago`,
    notifications: 0,
    isTyping: false,
    delivered: false,
    seen: false,
    photo: [`Elipse 17.png`],
  },
];
